#!/bin/bash

# Updates the master branch
composer install

required=("src" "vendor")
dependencies=("autoload.php" "composer" "illuminate/config" "illuminate/filesystem" "illuminate/translation" "mockery" "symfony", "predis")

# Create a temporary directory
rm -rf tmp
mkdir tmp

# Copy the important files in it
for file in "${required[@]}"
do
  echo "Copying $file"
  cp -R $file tmp/$file
done
cp ./* tmp/

# Remove unecessary dependencies
for dependency in "${dependencies[@]}"
do
  echo "Deleting vendor/$dependency"
  rm -rf tmp/vendor/$dependency
done

# Remove .git folders
for folder in tmp/vendor/*
do
  rm -rf $folder/{*,*/*,*/*/*}/.git
done

# Switch branch
git checkout master

# Delete current tree
rm -rf ./{tests,vendor,src}
rm -rf ./*.{xml,md,php,lock,json,yml}
rm -rf .gitignore

# Copy new one

cp -R tmp/* ./
rm -rf tmp/

git add .
git commit -m "Update master branch"
git push origin master